version: '3.8'
services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build: .
    image: techstaff/carlife
    ports:
      - '3030:3030'
    links:
      - mongo-db


